<?php


namespace frontend\controllers;


use common\models\AllBaiduKeywords;

class KeywordsController extends BaseController
{


    /**
     * @OA\Post(
     *     path="/keywords/pull",
     *     summary="关键词接收入口 【爬虫】",
     *     tags={"关键词"},
     *     description="",
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\MediaType(
     *             mediaType="multipart/form-data",
     *             @OA\Schema(
     *                 @OA\Property(
     *                     description="泛目录关键词id",
     *                     property="fan_key_id",
     *                     type="string",
     *                     format="query",
     *                     default="测试文章标题"
     *                 ),
     *                @OA\Property(
     *                     description="类型",
     *                     property="type",
     *                     type="string",
     *                     format="query",
     *                     default="spo",
     *                 ),
     *                @OA\Property(
     *                     description="关键词名称",
     *                     property="keywords",
     *                     type="string",
     *                     format="query",
     *                     default="会计老师在线咨询",
     *                 ),
     *               @OA\Property(
     *                     description="备注",
     *                     property="note",
     *                     type="string",
     *                     format="query",
     *                     default="会计",
     *                 ),
     *               @OA\Property(
     *                     description="移动端其他人还在搜",
     *                     property="m_search_name",
     *                     type="string",
     *                     format="query",
     *                     example="['会计是做什么的','学会计的基本条件','普通会计一个月多少钱','会计就业方向','会计的工资一般是多少','会计入门自学']"
     *                 ),
     *              @OA\Property(
     *                     description="移动端下拉词",
     *                     property="m_down_name",
     *                     type="integer",
     *                     format="query",
     *                     default="['会计证报考条件','会计','会计学','会计证报考条件2020年','会计自学','会计考试2020年考试时间','会计从业资格证报考时间2020年','会计是做什么的','会计怎样学','会计专业']",
     *                 ),
     *                @OA\Property(
     *                     description="移动端相关搜索",
     *                     property="m_related_name",
     *                     type="integer",
     *                     format="query",
     *                     default="[]",
     *                 ),
     *                @OA\Property(
     *                     description="移动端变种下拉词",
     *                     property="m_other_name",
     *                     type="integer",
     *                     format="query",
     *                     default="['会计证报考条件','会计哪里学最好','会计证培训班多少钱会计证','会计培训班会计培训','会计班课程','会计线上课程','会计老师在线咨询','会计在线咨询服务','会计班培训怎么报','会计在线答疑']",
     *                 ),
     *                @OA\Property(
     *                     description="域名id",
     *                     property="domain_id",
     *                     type="integer",
     *                     format="query",
     *                     default="1",
     *                 ),
     *                @OA\Property(
     *                     description="栏目id",
     *                     property="column_id",
     *                     type="integer",
     *                     format="query",
     *                     default="1",
     *                 ),
     *             )
     *         )
     *     ),
     *   @OA\Response(
     *     response=200,
     *     description="返回码",
     *     @OA\JsonContent( type="json", example=
     *     {
     *       "title_img": "标题图片",
     *       "title": "标题",
     *       "intro": "简介",
     *       "push_time": "发布时间",
     *     }
     *     )
     *   ),
     * )
     */
    public function actionPull()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }


    public function actionCallBack()
    {
        //关键词爬取回调
        $keywords = AllBaiduKeywords::findOne(\Yii::$app->request->get('key_id'));
        if (!empty($keywords)) {
            $keywords->back_time = date('Y-m-d H:i:s');
            $keywords->save(false);
            self::showMsg([]);
        } else {
            self::showMsg([],-1,'没有该关键词');
        }
    }
}